spring.application.name=s_jwt

# H2 Database Configuration
spring.datasource.url=jdbc:h2:mem:jwtdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.h2.console.enabled=true

# Hibernate Configuration
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

# JWT Configuration
jwt.secret=kMtC7KAkRby9Fri8VLIPHDICg0SV7OSlimZfRq1BY2e
jwt.exp=360000